# Generated by Django 2.0 on 2019-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producetype',
            name='type_image',
            field=models.ImageField(null=True, upload_to='produce', verbose_name='分类图片'),
        ),
    ]
