# Generated by Django 2.0 on 2019-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0004_produce_programe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='programetype',
            name='type_info',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
