# Generated by Django 2.0 on 2019-08-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0005_programetype_type_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceTypeTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('type_image', models.ImageField(null=True, upload_to='produce', verbose_name='分类图片')),
            ],
        ),
    ]
